# docker-compose.yml
services:
  app:
    build: .
    container_name: ${APP_NAME}_app
    volumes:
      - .:/app
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:1.21-alpine
    container_name: ${APP_NAME}_nginx
    ports:
      - "${APP_PORT:-8000}:80"
    volumes:
      - .:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: ${APP_NAME}_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  
  # New service for running Composer commands
  composer:
    image: composer:2
    container_name: ${APP_NAME}_composer
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
    driver: local
